trigger:
  branches:
    include:
      - maquina-isp-v5   # ou sua branch do GitHub
 
pool:
  vmImage: ubuntu-latest
 
steps:
- checkout: self
 
- task: AzureStaticWebApp@0
  displayName: "Deploy para Azure Static Web App"
  inputs:
    azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)
    app_location: "/"
    output_location: "/"