trigger:
  branches:
    include:
      - maquina-isp-v5
 
pool:
  vmImage: ubuntu-latest
 
variables:
- group: azure-static-web-apps-delightful-bush-0d5fe491e-variable-group
 
steps:
- checkout: self
 
- task: AzureStaticWebApp@0
  displayName: "Deploy para Azure Static Web App"
  inputs:
    azure_static_web_apps_api_token: $(AZURE_STATIC_WEB_APPS_API_TOKEN)
    app_location: "/"
    output_location: "/"